# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ThematicMapTools
                                 A QGIS plugin
 Tools for designing thematics maps
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-01-23
        copyright            : (C) 2021 by CamellONCase
        email                : camelloncase@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ThematicMapTools class from file ThematicMapTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .thematic_map_tools import ThematicMapTools
    return ThematicMapTools(iface)
